---
info:
  title: Rex Rop Builder
  description: Created by David Maloney via the GitHub Connector
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/rex-rop_builder
  x-cortex-tag: rex-rop-builder
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: metasploit
openapi: 3.0.1
servers:
- url: "/"
